### ISSUE TITLE
Update of main repository

### ISSUE THREAD

**Issue by felixplasser** [rlee287/TheoDORE_py3#1]
Hi, I just saw this fork by chance.

Just to let you know: The main TheoDORE repository on sourceforge is changed to python3 and that seems to work properly.

The one sore spot, which I also see in your notes, is still openbabel. I don't think there is an easy installation of python3/openbabel except if one goes through anaconda.

-Felix

**Comment by rlee287** [comment]
Readme updated and repo archived.
